
import ResponsiveMenu from '@/components/layout/ResponsiveMenu';
import MaterialProvider from '@/lib/MaterialProvider';
import { AppBar, Container, CssBaseline, ThemeProvider, Toolbar, Typography, createTheme } from '@mui/material';
import type { AppProps } from 'next/app';
import Head from 'next/head';



export default function ForumApp({ children }: { children: React.ReactNode }) {
  return (
    <html>

      <head>
        <title>Your App Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <MaterialProvider>
          <ResponsiveMenu />
          {children}
        </MaterialProvider>
      </body>
    </html>
  );
}
